language: java
jdk:
- oraclejdk8

sudo: required

services:
  - docker

branches:
  only:
  - master

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
      docker login -u $DOCKER_USER -p $DOCKER_PASS;
      export REPO=udlepssoftarch/mydata-api;
      export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`;
      docker build -f Dockerfile -t $REPO:$COMMIT .;
      docker tag $REPO:$COMMIT $REPO:$TAG;
      docker push $REPO;
      docker login --email=_ --username=_ --password=$HEROKU_TOKEN registry.heroku.com;
      docker tag $REPO:$COMMIT registry.heroku.com/mydata-api/web;
      docker push registry.heroku.com/mydata-api/web;
    fi

notifications:
  slack:
    on_success: change
    on_failure: always
    secure: gAgZ5QdYiZeEJhxeBRfCl2J8L5FBptq4eIMkrd/5+G+CLlseOupFwMD7PC3an5qclJwc6R77SD+4ZKy2ZeMrDc9ehyj9zrBYe3baVlk7nsEvSl+SUnHgjzEHM3fq07yEstIK3amRAUbWHtBqCfFQH3APVxYdpiPZEJK+k8X/xpDnvlDN5GxgYwPBzm79OuLJmC5mONvTcyZY8qd2FLrDnHjviUbU7/saF1ZBr9ScY4RTv88bRHXLcSTn3aQwEcNKGprdScEN80PzvO7Za851u+G6bn9VJgTq6jJmk19XivAUecZlub3O313CiiAsI6luprXziGxNesoFjN02UL1S/FTEbOmWrYPiMbO2QIIOmWevjX2Nluq0IrD7dZteTwNXG287SApXZrO0eenZbE8XszfdqxYBC8iKXn28GsEBTbxLzMpshcs5YCNZ9ManOAnhAZtq+a7e5uNFvcoTMwVcdecOyAkMpMpDyDjCZ9j6hFtQhaf8WQdM2j4ONxjHffxNan4f0y1wEZD1qw7ev0Iu+j5x00w9OSeB41cCx5cdaJ5mqyFosh8hgy4SIEOUuyDH8DscuILRzHmlxJvI+7b38YA9GPIYLa86rDKK8XQyqdlrUaVwQ6PnZWB8YReBYcyR38ibLkPJyOueVCOA9I3bUxQ0MA5OKAgUCVDUKsnioGQ=
