language: java
jdk:
- oraclejdk8
branches:
  only:
  - master
notifications:
  slack:
    on_success: change
    on_failure: always
    secure: gAgZ5QdYiZeEJhxeBRfCl2J8L5FBptq4eIMkrd/5+G+CLlseOupFwMD7PC3an5qclJwc6R77SD+4ZKy2ZeMrDc9ehyj9zrBYe3baVlk7nsEvSl+SUnHgjzEHM3fq07yEstIK3amRAUbWHtBqCfFQH3APVxYdpiPZEJK+k8X/xpDnvlDN5GxgYwPBzm79OuLJmC5mONvTcyZY8qd2FLrDnHjviUbU7/saF1ZBr9ScY4RTv88bRHXLcSTn3aQwEcNKGprdScEN80PzvO7Za851u+G6bn9VJgTq6jJmk19XivAUecZlub3O313CiiAsI6luprXziGxNesoFjN02UL1S/FTEbOmWrYPiMbO2QIIOmWevjX2Nluq0IrD7dZteTwNXG287SApXZrO0eenZbE8XszfdqxYBC8iKXn28GsEBTbxLzMpshcs5YCNZ9ManOAnhAZtq+a7e5uNFvcoTMwVcdecOyAkMpMpDyDjCZ9j6hFtQhaf8WQdM2j4ONxjHffxNan4f0y1wEZD1qw7ev0Iu+j5x00w9OSeB41cCx5cdaJ5mqyFosh8hgy4SIEOUuyDH8DscuILRzHmlxJvI+7b38YA9GPIYLa86rDKK8XQyqdlrUaVwQ6PnZWB8YReBYcyR38ibLkPJyOueVCOA9I3bUxQ0MA5OKAgUCVDUKsnioGQ=
deploy:
  provider: heroku
  strategy: git
  app:
    master: mydata-api
  api_key:
    secure: dsP2xR/Nl2HF+z7Pjm3LgjC1lhzpDEbbpDSgXI7zY1HTN4MGe+BJ6TalrxQ5fQCs52Fdx9GiG5PMfsiKvNy7f1TYR4KiFOJYEYWfqRjfivlLVxBhXPSfiqFuwGM6/rxDcDYCVRbsmkz9FTLQX3lZIHExhKUkNcQZC8Fcwn8/lc1ZghO6yzijIajLHbtFOWTT6+4/oudCXJqiEYVI+ErUiizcfsiZf+nyQqUsUYFBVoCtUegd3SIHkkPY8ZQq+uvlNxMfGiObMI/YJF6l/ZFFk9o7Dw6Zw9Z1rO03talbF2S+aw9N8tEAWhOX34VmzsRsXeEAMcrCutzASWjvE14zkohdf5dqR2aZfh25sxNtIkLFFJGebK/+LRR75tzcjZ+pCeCdnEfpP22MDVn/99YB59zN0CLxGrO4C6mWOfgBHgop7fN+ZeZ11Tp13KQeozqPjiab1OQat2+uMR4YcD7mw9hoBC9rRqMVyR/pei62g/BXycXBnnPlnWCE6gVbSNj1lk2yo2uGwOG0AMPHIp7jyjooiw3/F4qKtTxl6SyFV/qoP5oqXUfhJzU8K+W0zg3O7Z3e0+GCqQRT5ps/zowcNOYyDIib4UZnlkbFIcp6XO41Eku/ok5vZLWG41n810sSGaF1h68ft4YJdFX6sTI9ulI5CBYrfzcJf3p18EPBdcw=
